version: '3.3'

services:
    java:
        image: openjdk:8
        command: bash -c "cd /opt/minecraft && java -Xms1G -Xmx1G -jar server.jar"
        volumes:
            - ./data/minecraft:/opt/minecraft
        ports:
            - 25565:25565
